group 'com.jiguang.jverify'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
    }
}

rootProject.allprojects {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    namespace "com.jiguang.jverify"
    compileSdkVersion 33


    defaultConfig {
        minSdkVersion 19
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    lintOptions {
        disable 'InvalidPackage'
    }

}

dependencies {
//    implementation fileTree(include: '*.aar', dir: 'libs')
    implementation ('cn.jiguang.sdk:jverification:3.4.2') {
        exclude group: 'cn.jiguang.sdk', module: 'jcore'//会自动把jcore剔除
    }
    implementation 'cn.jiguang.sdk:jcore:4.9.1'
}
